data:
  dream_text_file_path: "datasets/rsos_dream_data.tsv"
  keywords_file_path: "datasets/augmented_25.05.13-17.csv"
  dream_text_column: "text_dream"
  keywords_column: "context"
  interpretation_column: "meaning"

model:
  name: 'all-MiniLM-L6-v2'
  num_keywords: 5
  num_semantic: 50
  diversity: 0.7
